✨ feat: other_npo.htmlの更新
Kokecoco/KITs pull request #74
Opened 2024-11-15 01:55 UTC by Sota000-1

# 実施内容
- other_npo.htmlの更新

# レビューして欲しいところ
- バグチェック

# 備考
なし

2024-11-15 16:25 UTC, YouTuber-repopo requested changes
"AUS"ではなく正しくは"Aus"です

2024-11-23 02:30 UTC, Kokecoco requested changes
"Lieilat"ではなく"Liella!"、"先生を訪ねて３千里"ではなく"先生を訪ねて三千里"です。

2024-11-23 09:50 UTC, YouTuber-repopo approved these changes
OK!

2024-11-23 09:54 UTC, Kokecoco approved these changes

2024-11-23 09:55 UTC, merged